project:
  type: website
  output-dir: docs



website:
  title: "Family Search Senior Project"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/SpencerJHowe

format:
  html:
    theme: cosmo
    css: styles.css



